// flow-typed signature: 632648814dd34f21af5b0519297acfdb
// flow-typed version: <<STUB>>/systeminformation_v^3.49.3/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'systeminformation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'systeminformation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'systeminformation/lib/battery' {
  declare module.exports: any;
}

declare module 'systeminformation/lib/cpu' {
  declare module.exports: any;
}

declare module 'systeminformation/lib/docker' {
  declare module.exports: any;
}

declare module 'systeminformation/lib/dockerSocket' {
  declare module.exports: any;
}

declare module 'systeminformation/lib/filesystem' {
  declare module.exports: any;
}

declare module 'systeminformation/lib/graphics' {
  declare module.exports: any;
}

declare module 'systeminformation/lib/index' {
  declare module.exports: any;
}

declare module 'systeminformation/lib/internet' {
  declare module.exports: any;
}

declare module 'systeminformation/lib/memory' {
  declare module.exports: any;
}

declare module 'systeminformation/lib/network' {
  declare module.exports: any;
}

declare module 'systeminformation/lib/osinfo' {
  declare module.exports: any;
}

declare module 'systeminformation/lib/processes' {
  declare module.exports: any;
}

declare module 'systeminformation/lib/system' {
  declare module.exports: any;
}

declare module 'systeminformation/lib/users' {
  declare module.exports: any;
}

declare module 'systeminformation/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'systeminformation/lib/battery.js' {
  declare module.exports: $Exports<'systeminformation/lib/battery'>;
}
declare module 'systeminformation/lib/cpu.js' {
  declare module.exports: $Exports<'systeminformation/lib/cpu'>;
}
declare module 'systeminformation/lib/docker.js' {
  declare module.exports: $Exports<'systeminformation/lib/docker'>;
}
declare module 'systeminformation/lib/dockerSocket.js' {
  declare module.exports: $Exports<'systeminformation/lib/dockerSocket'>;
}
declare module 'systeminformation/lib/filesystem.js' {
  declare module.exports: $Exports<'systeminformation/lib/filesystem'>;
}
declare module 'systeminformation/lib/graphics.js' {
  declare module.exports: $Exports<'systeminformation/lib/graphics'>;
}
declare module 'systeminformation/lib/index.js' {
  declare module.exports: $Exports<'systeminformation/lib/index'>;
}
declare module 'systeminformation/lib/internet.js' {
  declare module.exports: $Exports<'systeminformation/lib/internet'>;
}
declare module 'systeminformation/lib/memory.js' {
  declare module.exports: $Exports<'systeminformation/lib/memory'>;
}
declare module 'systeminformation/lib/network.js' {
  declare module.exports: $Exports<'systeminformation/lib/network'>;
}
declare module 'systeminformation/lib/osinfo.js' {
  declare module.exports: $Exports<'systeminformation/lib/osinfo'>;
}
declare module 'systeminformation/lib/processes.js' {
  declare module.exports: $Exports<'systeminformation/lib/processes'>;
}
declare module 'systeminformation/lib/system.js' {
  declare module.exports: $Exports<'systeminformation/lib/system'>;
}
declare module 'systeminformation/lib/users.js' {
  declare module.exports: $Exports<'systeminformation/lib/users'>;
}
declare module 'systeminformation/lib/util.js' {
  declare module.exports: $Exports<'systeminformation/lib/util'>;
}
